filetype plugin indent on

augroup FiletypeSpecificIndents
  autocmd FileType lilypond setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
  autocmd FileType vim setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
augroup END
