HOME_CONFIG_DIR="$HOME/.config"
SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
SOURCE_TMUX_CONF_PATH="$SCRIPT_DIR/tmux.conf"
TMUX_CONFIG_DIR="$HOME_CONFIG_DIR/tmux"
TARGET_TMUX_CONF_PATH="$TMUX_CONFIG_DIR/tmux.conf"

mkdir -p "$TMUX_CONFIG_DIR"
cp -i "$SOURCE_TMUX_CONF_PATH" "$TMUX_CONFIG_DIR"
