HOME_CONFIG_DIR="$HOME/.config"
SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
SOURCE_TMUX_CONF_PATH="$SCRIPT_DIR/tmux.conf"
TARGET_TMUX_CONF_PATH="$HOME_CONFIG_DIR/tmux.conf"

mkdir -p "$HOME_CONFIG_DIR"
cp -i "$SOURCE_TMUX_CONF_PATH" "$TARGET_TMUX_CONF_PATH"
